include_directories(${CMAKE_CURRENT_LIST_DIR})

if (NOT DEFINED XSCANENGINE_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/xscanengine.cmake)
    set(XSCANENGINECONSOLE_SOURCES ${XSCANENGINECONSOLE_SOURCES} ${XSCANENGINE_SOURCES})
endif()

if (NOT DEFINED XFMODEL_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../Formats/xfmodel.cmake)
    set(XSCANENGINECONSOLE_SOURCES ${XSCANENGINECONSOLE_SOURCES} ${XFMODEL_SOURCES})
endif()

set(XSCANENGINECONSOLE_SOURCES
    ${XSCANENGINECONSOLE_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/xscanengineconsole.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xscanengineconsole.h
)
