cmake_minimum_required(VERSION 3.16)
project(test_native_primitives LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_AUTOMOC ON)
find_package(Qt5 REQUIRED COMPONENTS Core Qml Script)
add_executable(test_native_primitives test_native_primitives.cpp)
target_link_libraries(test_native_primitives PRIVATE Qt5::Core Qt5::Qml Qt5::Script)
enable_testing()
add_test(NAME test_native_primitives COMMAND test_native_primitives)
